#!/bin/bash

# ==============================================================================
#  Code Ocean Main Execution File
#  Manuscript: "Single-molecule sensing by deep-learning-decoded..."
#  This script provides instructions for reproducing the results.
# ==============================================================================

BOLD=$(tput bold)
BLUE=$(tput setaf 4)
GREEN=$(tput setaf 2)
NC=$(tput sgr0)

echo ""
echo "${BLUE}${BOLD}======================================================================${NC}"
echo "${BLUE}${BOLD}  Instructions for Reproducing Manuscript Results                     ${NC}"
echo "${BLUE}${BOLD}======================================================================${NC}"
echo ""
echo "This project contains several Jupyter Notebooks, each corresponding to a"
echo "specific analysis presented in the manuscript. Due to the modular and"
echo "interactive nature of the analyses, this script does not execute them"
echo "automatically. Instead, please follow the instructions below."
echo ""
echo "You can open and run the cells in each notebook sequentially."
echo ""
echo "${GREEN} Data Preprocessing for Deep Learning:${NC}"
echo "   - ${BOLD}File:${NC} Data-Preprocesing.ipynb"
echo "   - ${BOLD}Description:${NC} This notebook processes the data preprocessing for deep learning applications."
echo ""

echo "${GREEN} Spectral Clustering Analysis (Benchmark Method):${NC}"
echo "   - ${BOLD}File:${NC} SpectrumClustering.ipynb"
echo "   - ${BOLD}Description:${NC} This notebook contains the code for spectral clustering analysis."
echo ""

echo "${GREEN}Classifier (CuP+CAF) (Deep Learning Method):${NC}"
echo "   - ${BOLD}File:${NC} Classifier(CuP+CAF).ipynb"
echo "   - ${BOLD}Description:${NC} This notebook contains the code for training the classifier and presenting the results."
echo ""
echo "${GREEN}Classifier (CuP+PTX) (Deep Learning Method):${NC}"
echo "   - ${BOLD}File:${NC} Classifier(CuP+PTX).ipynb"
echo "   - ${BOLD}Description:${NC} This notebook contains the code for training the classifier and presenting the results."
echo ""
echo "${GREEN}Classifier (CuP+TPH) (Deep Learning Method):${NC}"
echo "   - ${BOLD}File:${NC} Classifier(CuP+TPH).ipynb"
echo "   - ${BOLD}Description:${NC} This notebook contains the code for training the classifier and presenting the results."
echo ""
echo "${GREEN}Classifier (FP+CAF) (Deep Learning Method):${NC}"
echo "   - ${BOLD}File:${NC} Classifier(FP+CAF).ipynb"
echo "   - ${BOLD}Description:${NC} This notebook contains the code for training the classifier and presenting the results."
echo ""

echo "${GREEN}G0-shift Robustness Experiment (Supplementary Experiment):${NC}"
echo "   - ${BOLD}File:${NC} G0-shift robustness experiment.ipynb"
echo "   - ${BOLD}Description:${NC} This notebook contains the code for G0-shift robustness experiment."
echo ""
echo "${GREEN}Occlusion Sensitivity Analysis (Supplementary Experiment):${NC}"
echo "   - ${BOLD}File:${NC} Occlusion Sensitivity Analysis.ipynb"
echo "   - ${BOLD}Description:${NC} This notebook contains the code for occlusion sensitivity analysis."
echo ""
echo "${GREEN}Random Background Truncation Experiment (Supplementary Experiment):${NC}"
echo "   - ${BOLD}File:${NC} Random background truncation experiment.ipynb"
echo "   - ${BOLD}Description:${NC} This notebook contains the code for random background truncation experiment."
echo ""

echo "${GREEN}Ablation Experiment Both (CuP+CAF) (Ablation Experiment):${NC}"
echo "   - ${BOLD}File:${NC} Ablation experiment-both(CuP+CAF).ipynb"
echo "   - ${BOLD}Description:${NC} This notebook contains the code for conducting the ablation experiment (time- and frequency-domain)"
echo ""
echo "${GREEN}Ablation Experiment Both (CuP+PTX) (Ablation Experiment):${NC}"
echo "   - ${BOLD}File:${NC} Ablation experiment-both(CuP+PTX).ipynb"
echo "   - ${BOLD}Description:${NC} This notebook contains the code for conducting the ablation experiment (time- and frequency-domain)"
echo ""
echo "${GREEN}Ablation Experiment Both (CuP+TPH) (Ablation Experiment):${NC}"
echo "   - ${BOLD}File:${NC} Ablation experiment-both(CuP+TPH).ipynb"
echo "   - ${BOLD}Description:${NC} This notebook contains the code for conducting the ablation experiment (time- and frequency-domain)"
echo ""
echo "${GREEN}Ablation Experiment Both (FP+CAF) (Ablation Experiment):${NC}"
echo "   - ${BOLD}File:${NC} Ablation experiment-both(FP+CAF).ipynb"
echo "   - ${BOLD}Description:${NC} This notebook contains the code for conducting the ablation experiment (time- and frequency-domain)"
echo ""

echo "${GREEN}Ablation Experiment Onlyfreq (CuP+CAF) (Ablation Experiment):${NC}"
echo "   - ${BOLD}File:${NC} Ablation experiment-Onlyfreq(CuP+CAF).ipynb"
echo "   - ${BOLD}Description:${NC} This notebook contains the code for conducting the ablation experiment (frequency-domain)"
echo ""
echo "${GREEN}Ablation Experiment Onlyfreq (CuP+PTX) (Ablation Experiment):${NC}"
echo "   - ${BOLD}File:${NC} Ablation experiment-Onlyfreq(CuP+PTX).ipynb"
echo "   - ${BOLD}Description:${NC} This notebook contains the code for conducting the ablation experiment (frequency-domain)"
echo ""
echo "${GREEN}Ablation Experiment Onlyfreq (CuP+TPH) (Ablation Experiment):${NC}"
echo "   - ${BOLD}File:${NC} Ablation experiment-Onlyfreq(CuP+TPH).ipynb"
echo "   - ${BOLD}Description:${NC} This notebook contains the code for conducting the ablation experiment (frequency-domain)"
echo ""
echo "${GREEN}Ablation Experiment Onlyfreq (FP+CAF) (Ablation Experiment):${NC}"
echo "   - ${BOLD}File:${NC} Ablation experiment-Onlyfreq(FP+CAF).ipynb"
echo "   - ${BOLD}Description:${NC} This notebook contains the code for conducting the ablation experiment (frequency-domain)"
echo ""

echo "${GREEN}Ablation Experiment Onlytime (CuP+CAF) (Ablation Experiment):${NC}"
echo "   - ${BOLD}File:${NC} Ablation experiment-Onlytime(CuP+CAF).ipynb"
echo "   - ${BOLD}Description:${NC} This notebook contains the code for conducting the ablation experiment (time-domain)"
echo ""
echo "${GREEN}Ablation Experiment Onlytime (CuP+PTX) (Ablation Experiment):${NC}"
echo "   - ${BOLD}File:${NC} Ablation experiment-Onlytime(CuP+PTX).ipynb"
echo "   - ${BOLD}Description:${NC} This notebook contains the code for conducting the ablation experiment (time-domain)"
echo ""
echo "${GREEN}Ablation Experiment Onlytime (CuP+TPH) (Ablation Experiment):${NC}"
echo "   - ${BOLD}File:${NC} Ablation experiment-Onlytime(CuP+TPH).ipynb"
echo "   - ${BOLD}Description:${NC} This notebook contains the code for conducting the ablation experiment (time-domain)"
echo ""
echo "${GREEN}Ablation Experiment Onlytime (FP+CAF) (Ablation Experiment):${NC}"
echo "   - ${BOLD}File:${NC} Ablation experiment-Onlytime(FP+CAF).ipynb"
echo "   - ${BOLD}Description:${NC} This notebook contains the code for conducting the ablation experiment (time-domain)"
echo ""

echo "${BLUE}${BOLD}======================================================================${NC}"
echo "End."
echo "${BLUE}${BOLD}======================================================================${NC}"
echo ""